# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  name: us-east1-docker.pkg.dev/task-project-374915/argotestrepo/image_my_repo
  tag: c1.1
